### ISSUE TITLE
runBroadcast isn't an event

### ISSUE THREAD

**Issue by Chirou-Cat** [CreaturePhil/Showdown-Boilerplate#88]
srsly dude, I've had to pick up your pieces and fix all your bugs, Why can't you actually code for once, What happened, Did you hit your head or something?

**Comment by TheFenderStory** [comment]
Can you give us more details about the bug? An error stack or test case we can use would be much appreciated. I can't seem to recreate the issue locally executing commands with runBroadcast.

**Comment by CreaturePhil** [comment]
@Chirou-Cat Please provide more information like @TheFenderStory said instead of a vague phrase naming a function that is used in almost all commands. Also your attitude reminds me of tenshihan from this github issue: https://github.com/ParsePlatform/parse-server/issues/1050. I wouldn't be surprise if you guys are related by blood.

**Comment by Chirou-Cat** [comment]
"I'm so sick you github shitter junkies" <-- Sorry what does he English? 

Also I am going to replicate the bug now

**Comment by Chirou-Cat** [comment]
POKEMON SHOWDOWN HAS CRASHED: TypeError: this.runBroadcast is not a function
at CommandContext.exports.commands.wallet (E:\Showdown-Boilerplate-master\chat-plugins\economy.js:143:13)

k tnx for wasting my time to replicate this

**Comment by CreaturePhil** [comment]
@Chirou-Cat I'm testing this locally and could not replicate this bug. Are you using the whole Showdown-Boilerplate repository or just copying economy.js into your Pokemon-Showdown repository?

**Comment by Chirou-Cat** [comment]
im using the whole thing

**Comment by CreaturePhil** [comment]
@Chirou-Cat Can you show the whole stack trace?

**Comment by Chirou-Cat** [comment]
CRASH: TypeError: this.runBroadcast is not a function
    at CommandContext.exports.commands.wallet (E:\Showdown-Boilerplate-master\chat-plugins\economy.js:143:13)
    at CommandContext.run (E:\Showdown-Boilerplate-master\command-parser.js:223:28)
    at Object.exports.parse (E:\Showdown-Boilerplate-master\command-parser.js:554:18)
    at Room.chat (E:\Showdown-Boilerplate-master\rooms.js:103:27)
    at User.chat (E:\Showdown-Boilerplate-master\users.js:1590:9)
    at Function.ip.rename.connection.validateRename.challenge.getAlts.getAll.ban.userid.lock.userid.leaveRoom.force.prepBattle.connection.static.pruneInactive.Users.socketConnect.fs.appendFile.require.randomBytes.Users.socketReceive.message [as socketReceive] (E:\Showdown-Boilerplate-master\users.js
:1810:12)
    at ChildProcess.<anonymous> (E:\Showdown-Boilerplate-master\sockets-nocluster.js:54:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)

Additional information:
  user = Strawberry Delight
  room = lobby
  message = /atm



CRASH: TypeError: this.runBroadcast is not a function
    at CommandContext.exports.commands.wallet (E:\Showdown-Boilerplate-master\chat-plugins\economy.js:143:13)
    at CommandContext.run (E:\Showdown-Boilerplate-master\command-parser.js:223:28)
    at Object.exports.parse (E:\Showdown-Boilerplate-master\command-parser.js:554:18)
    at Room.chat (E:\Showdown-Boilerplate-master\rooms.js:103:27)
    at User.chat (E:\Showdown-Boilerplate-master\users.js:1590:9)
    at Function.ip.rename.connection.validateRename.challenge.getAlts.getAll.ban.userid.lock.userid.leaveRoom.force.prepBattle.connection.static.pruneInactive.Users.socketConnect.fs.appendFile.require.randomBytes.Users.socketReceive.message [as socketReceive] (E:\Showdown-Boilerplate-master\users.js
:1810:12)
    at ChildProcess.<anonymous> (E:\Showdown-Boilerplate-master\sockets-nocluster.js:54:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)

Additional information:
  user = Silvernyan321
  room = lobby
  message = /atm

**Comment by panpawn** [comment]
lol

**Comment by supersoniko** [comment]
Downloading brain.js should solve this problem.

**Comment by CreaturePhil** [comment]
This issue cannot be reproduce. Make sure you got runBroadcast in context object of the command-parser.js file.
